module Rubix
  autoload :Model,           'rubix/models/model'
  autoload :HostGroup,       'rubix/models/host_group'
  autoload :Template,        'rubix/models/template'
  autoload :Host,            'rubix/models/host'
  autoload :Item,            'rubix/models/item'
  autoload :Application,     'rubix/models/application'
  autoload :UserMacro,       'rubix/models/user_macro'
  autoload :Trigger,         'rubix/models/trigger'
  autoload :TimeSeries,      'rubix/models/time_series'
  autoload :MediaType,       'rubix/models/media_type'
  autoload :Script,          'rubix/models/script'
  autoload :Action,          'rubix/models/action'
  autoload :Condition,       'rubix/models/condition'
  autoload :Operation,       'rubix/models/operation'
  autoload :User,            'rubix/models/user'
  autoload :UserGroup,       'rubix/models/user_group'
  autoload :Medium,          'rubix/models/medium'
  autoload :Interface,       'rubix/models/interface'
  autoload :Inventory,       'rubix/models/inventory'
  autoload :Graph,           'rubix/models/graph'
  autoload :Screen,          'rubix/models/screen'
  autoload :ScreenItem,      'rubix/models/screen_item'
  autoload :Message,         'rubix/models/message'
end
